create or replace table "RONALDO"."PUBLIC"."DIM_MATCH_INFO" (
    MATCH_ID integer not null,
    OPPONENT TEXT,
    GAME_SEASON TEXT,
    KNOCKOUT_MATCH TEXT,
    HOME_AWAY TEXT,
   DATE_OF_GAME DATE,
    TIMESTAMP DATE,
    constraint MATCH_ID primary key (MATCH_ID) not enforced
    );

insert into "RONALDO"."PUBLIC"."DIM_MATCH_INFO"

with cte1 as (
select  
MATCH_ID,
Coalesce(GAME_SEASON,LAG(GAME_SEASON) IGNORE NULLS OVER (partition by MATCH_ID ORDER BY MATCH_ID)) as GAME_SEASON, 
Coalesce(HOME_AWAY,LAG(HOME_AWAY) IGNORE NULLS OVER (partition by MATCH_ID ORDER BY MATCH_ID)) as HOME_AWAY,
Coalesce(LAT_LNG,LAG(LAT_LNG) IGNORE NULLS OVER (partition by MATCH_ID ORDER BY MATCH_ID)) as LAT_LNG,
Coalesce(KNOCKOUT_MATCH,LAG(KNOCKOUT_MATCH) IGNORE NULLS OVER (partition by MATCH_ID ORDER BY MATCH_ID)) as KNOCKOUT_MATCH,
Coalesce(DATE_OF_GAME,LAG(DATE_OF_GAME) IGNORE NULLS OVER (partition by MATCH_ID ORDER BY MATCH_ID)) as DATE_OF_GAME
from "RONALDO"."PUBLIC"."RONALDO_CAREER_STAGING_TABLE"
where  MATCH_ID NOT IN  (select MATCH_ID from "RONALDO"."PUBLIC"."DIM_MATCH_INFO")
),

cte2 as (
select
MATCH_ID,
Coalesce(GAME_SEASON,LEAD(GAME_SEASON) IGNORE NULLS OVER (partition by MATCH_ID ORDER BY MATCH_ID)) as GAME_SEASON, 
Coalesce(HOME_AWAY,LEAD(HOME_AWAY) IGNORE NULLS OVER (partition by MATCH_ID ORDER BY MATCH_ID)) as OPPONENT,
Coalesce(LAT_LNG,LEAD(LAT_LNG) IGNORE NULLS OVER (partition by MATCH_ID ORDER BY MATCH_ID)) as LAT_LNG,
Coalesce(KNOCKOUT_MATCH,LEAD(KNOCKOUT_MATCH) IGNORE NULLS OVER (partition by MATCH_ID ORDER BY MATCH_ID)) as KNOCKOUT_MATCH,
Coalesce(DATE_OF_GAME,LEAD(DATE_OF_GAME) IGNORE NULLS OVER (partition by MATCH_ID ORDER BY MATCH_ID)) as DATE_OF_GAME
from cte1
),

cte3 as (
select
MATCH_ID,
GAME_SEASON,
OPPONENT,
KNOCKOUT_MATCH,
DATE_OF_GAME,
CASE
    WHEN contains(LAT_LNG,'42.982923  -71.446094') THEN 'HOME'
    ELSE 'AWAY'
    END as HOME_AWAY
  from cte2
where GAME_SEASON is not null and 
HOME_AWAY is not null and 
LAT_LNG is not null and 
KNOCKOUT_MATCH is not null and
DATE_OF_GAME is not null
),

cte4 as  (
select distinct MATCH_ID,OPPONENT,GAME_SEASON,KNOCKOUT_MATCH,HOME_AWAY,DATE_OF_GAME from cte3
),

cte5 as (
  select *,ROW_NUMBER() OVER (PARTITION BY MATCH_ID ORDER BY MATCH_ID) RNO from cte4
  )
  
select MATCH_ID,OPPONENT,GAME_SEASON,KNOCKOUT_MATCH,
HOME_AWAY,DATE_OF_GAME,to_date(CURRENT_TIMESTAMP) as timestamp from cte5 where RNO = 1 order by MATCH_ID;

select * from "RONALDO"."PUBLIC"."DIM_MATCH_INFO"
